### PR TITLE
Address #771

### PR DESCRIPTION
**Pull request by pdonahue-ventana**
/cc @silabs-robin

### CODE REVIEW

**Review by timsifive — APPROVED** [review]

**Review by Silabs-ArjanB — COMMENTED** [review]
It would be nice if it would be made clear that several implementations are possible. E.g. the burden of 'not disallowing fetches' could either be put on hardware (i.e. bypassing PMP for certain accesses) or on software (i.e. configuring PMP taking debug into account)

**Comment by Silabs-ArjanB** [comment]
Bypassing the PMP (and possibly other checks) by hardware sounds like a security hole to me. If the PMP is always being bypassed (and accesses to the debug region always allowed), then software running on the hart itself has no way of prohibiting debug mode execution. (Of course the entire debug module can be made inaccessible, but that protection is at a different level in the design)

**Comment by timsifive** [comment]
I'm not talking about bypassing the entire PMP. The requirement says:
> The PMP must not disallow fetches, loads, or stores in the address range associated with the Debug Module when the hart is in Debug Mode

Can you elaborate on the security hole you see with that? I don't exactly follow it.

**Comment by Silabs-ArjanB** [comment]
Suppose that software specifically forbids execution based debug by configuring the PMP to disallow execution from the 'debug region'. If these PMP settings are overruled by allowing the CPU to execute from the debug region anyway, then I would consider that a security hole. Of course the adversary would need to have JTAG access allowed to the debug module as well (which can have its own protection mechanism), but disallowing it from software via the PMP would be a nice fail safe on top of that.

>> Having debug only work if the software plays along seems like a recipe for a poor debugging experience.

Another (non debug related) example: Suppose code execution is only allowed from some internal Flash. If you use the PMP you would have to set it up to allow code execution from Flash. Failing to do so would then also be judged a 'poor execution from Flash experience'... and if the same reasoning would apply then the PMP would need to be bypassed to always allow code execution from Flash ... this doesn't make sense in my opinion. People should just properly program the PMP.

**Comment by timsifive** [comment]
> Suppose code execution is only allowed from some internal Flash. If you use the PMP you would have to set it up to allow code execution from Flash. Failing to do so would then also be judged a 'poor execution from Flash experience'

True, but the existence of an address range associated with a Debug Module is an implementation detail. There is no mechanism for software to discover this exists, or where it is. What's more, Debug Mode is essentially a mode that is more privileged than Machine Mode. It seems counterintuitive to have code in one mode prevent code in a more privileged mode from doing something.

Allowing software to prevent itself from being debugged externally is not a design goal. Maybe it should be, but that would have more impact beyond what we say in this appendix.

**Review by silabs-robin — APPROVED** [review]
Approving based on:
1. The changes to the text resolves the ambiguity.
2. The discussion seems to have converged.

**Pull request merged**
