### PR TITLE
Don't decrement icount.count when exception is blocked by tcontrol.mte

### PR DESCRIPTION
**Pull request by scottj97**
See #555.

I have not tested this change by building a PDF (or anything else).

cc @ernie-sifive

### CODE REVIEW

**Review by ernie-sifive — APPROVED** [review]
This looks good to me.

**Review by timsifive — CHANGES_REQUESTED** [review]
I'd write this as:
            When set, every instruction completed in or trap taken from
            M-mode decrements \FcsrIcountCount by 1, unless \FcsrTcontrolMte and
            \FcsrIcountAction are both 0.

I don't think any existing behavior is contingent on tcontrol being implemented. If it's not implemented, then mte is assumed to always be 0, which is the simpler behavior. Making triggers work in M mode is really a fancy corner case. Generally if you're debugging M mode software you're using an external debugger.

**Comment by scottj97** [comment]
> 
> 
> I'd write this as:
> When set, every instruction completed in or trap taken from
> M-mode decrements \FcsrIcountCount by 1, unless \FcsrTcontrolMte and
> \FcsrIcountAction are both 0.
> 
> I don't think any existing behavior is contingent on tcontrol being implemented. If it's not implemented, then mte is assumed to always be 0, which is the simpler behavior. Making triggers work in M mode is really a fancy corner case. Generally if you're debugging M mode software you're using an external debugger.

I don't think mte is assumed to be 0 if tcontrol is not implemented. If it were, this statement in 5.4 would not make sense: "The simple solution is to have the hardware prevent triggers with action=0 from firing while in M mode and while MIE in mstatus is 0. Its limitation is that interrupts might be disabled at other times when a user might want triggers to fire."

If mte were assumed to be 0 then there would be no need to consider MIE as the trap would already be blocked.

**Comment by scottj97** [comment]
Though that does bring up an interesting point. If an implementation uses the `mstatus.MIE` mechanism to block M-mode breakpoints, perhaps that should also suppress the decrement of `count`, for the same reasons.

**Comment by scottj97** [comment]
I've pushed another commit that simplifies the description by referring to section 5.4.

**Review by ernie-sifive — APPROVED** [review]
This wording is better, thanks.

**Review by timsifive — APPROVED** [review]
I'll merge this tomorrow, pending more comments.

**Comment by scottj97** [comment]
I guess this should have the "Backwards Incompatible Change" label?

**Comment by scottj97** [comment]
Note that this has been reversed by #574 since that change makes this problem moot.

**Pull request merged**
