### PR TITLE
Change version to 1.0.0-rc1 (frozen); rebuild PDF.

### PR DESCRIPTION
**Pull request by rtwfroody**
https://lists.riscv.org/g/tech-committee-chairs/message/474 links to an email showing that we're approved for freeze, but that email is not publically available.

### CODE REVIEW

**Comment by jjscheel** [comment]
Please make sure the text in the Preface reflects that the document is frozen.  You can view the appropriate text in the [Specification States wiki page](https://wiki.riscv.org/display/HOME/Specification+States).

**Comment by rtwfroody** [comment]
> Please make sure the text in the Preface reflects that the document is frozen. You can view the appropriate text in the Specification States wiki page.

I've incorporated that text. Thanks.

**Review by pdonahue-ventana — COMMENTED** [review]
Frankly, I haven't run "make" in months.  I just tried it on this branch and I get an error that serial.tex is not found.  It's happy if I change the reference in future.tex from serial.tex to serial.tex.inc.

**Comment by rtwfroody** [comment]
Hmm... future.tex is vestigial and shouldn't be included anywhere. I've removed it. Can you see if it works now?

**Review by pdonahue-ventana — APPROVED** [review]
That explains why I couldn't find the content of future.tex in the spec.  Anyway, `make` now runs cleanly for me and the other changes seem fine.

**Pull request merged**
