### PR TITLE
Clarify Memory Access acts like data access.

### PR DESCRIPTION
**Pull request by rtwfroody**
I'm not sure if this is necessary. Does RISC-V allow data loads to differ from instruction fetches? For a long time any mention of caches was avoided in all specs.

Inspired by #1062.

### CODE REVIEW

**Comment by pdonahue-ventana** [comment]
> Does RISC-V allow data loads to differ from instruction fetches?

Yes.  The Zifencei chapter of the unpriv spec says: "RISC-V does not guarantee that stores to instruction memory will be made visible to instruction fetches on a RISC-V hart until that hart executes a FENCE.I instruction."

**Review by pdonahue-ventana — COMMENTED** [review]
I would say something more like "This command lets the debugger perform memory accesses, with the exact same memory view and permissions as performing a load/store on the selected hart."  Then that leads nicely into the next sentence about memory-mapped registers.

**Comment by rtwfroody** [comment]
@pdonahue-ventana sounds good. Changed.

**Review by pdonahue-ventana — APPROVED** [review]
Great

**Pull request merged**
