### PR TITLE
Bump version to 0.13.1.

### PR DESCRIPTION
**Pull request by timsifive**

### CODE REVIEW

**Comment by timsifive** [comment]
Can I get a review on this?

**Comment by mwachs5** [comment]
Should we make an `0.13.1` branch for this vs pushing to the current `master`? Is the idea to keep bumping the minor version number every time we add a change, or...?

**Comment by timsifive** [comment]
`master` should always point to the latest work in progress, which currently is 0.13.1-DRAFT. We'll keep using 0.13.1-DRAFT until that gets ratified as 0.13.1, or until we need to make incompatible changes. (At that point we may end up with a compatible and incompatible branch.)

**Comment by mwachs5** [comment]
Why don't we create a tag for 0.13, and then explain the above rationale in the README for this repository, also pointing people to the errata document (or maybe that goes in the other PR)

**Comment by timsifive** [comment]
I was going to create a tag for 0.13 once it's ratified, to avoid the case of us tagging something that turns out not to be true. Once that is created, I agree it's a good idea to update the README. Currently there is a tag for what we sent off to be ratified.

**Comment by timsifive** [comment]
Can you continue this discussion/approve the change?

**Pull request merged**
