### PR TITLE
Address https://github.com/riscv/riscv-debug-spec/issues/985

### PR DESCRIPTION
**Pull request by pdonahue-ventana**
I believe that this bug fix should be addressed before ratification.

/cc @en-sc

### CODE REVIEW

**Comment by rtwfroody** [comment]
Since the spec is frozen, I think we need to run this through architecture review. Can you rebase and submit this PR to be relative to rc2? Then we can include it in the batch of changes I was going to send over there today but haven't yet, so we can still squeeze this in.

**Comment by pdonahue-ventana** [comment]
I just rebased to rc2.

**Comment by pdonahue-ventana** [comment]
Well, that doesn't look right.  Did you want me to rebase to rc2 and have the PR merge into rc2?  I don't know how to change the target branch of the PR.

**Comment by pdonahue-ventana** [comment]
I think that I figured that out but now there are additional changes that we already dealt with in different PRs.

**Comment by pdonahue-ventana** [comment]
OK.  We can close this.

**Pull request closed without merging**
