### PR TITLE
mte/mpte apply only to breakpoint traps

### PR DESCRIPTION
**Pull request by timsifive**
This makes it possible to use triggers to debug some of the exception
handling code as well.

See 2022 email subject:"trigger questions"

### CODE REVIEW

**Comment by pdonahue-ventana** [comment]
This seems like it's not backwards compatible.  I think that a note should be added to 1.2.1.5.

**Comment by timsifive** [comment]
Huh. I'd written that but not pushed it up yet. Here it is.

**Review by pdonahue-ventana — APPROVED** [review]
Sounds good.

**Comment by timsifive** [comment]
The e-mail thread about this really starts at https://lists.riscv.org/g/tech-debug/topic/89848254#691.

This change solves some problems when stepping into exception handlers when native debugging the highest privilege mode. (This is really the ideal use case for external debug, but we try to accommodate native debugging here as well.) If every trap into M-Mode clears mte, then you can't use icount triggers to step into an exception handler. By limiting this clearing to breakpoint exceptions only, more code can be debugged.

**Comment by timsifive** [comment]
AR feedback is that this change results in the mechanism not serving its purpose when non-breakpoint traps occur.

That sounds right to me. Consider:
1. icount is set so that it'll trigger on the first instruction of an exception handler.
2. Code takes an exception, saving mepc etc.
3. Now icount fires causing a breakpoint exception, clobbering mepc.

@pdonahue-ventana can you look this over? You have a gift for corner cases.

**Pull request merged**
