### PR TITLE
Reset clarifications 

### PR DESCRIPTION
**Pull request by mwachs5**
* Add explanation about how \Fndmreset and actual system reset are related (addresses #120)
* Also clarify that havereset bits may or may not be ~~are not~~ affected by dmactive low (addresses #169)

### CODE REVIEW

**Comment by timsifive** [comment]
Why aren't the havereset bits affected by dmactive going low? I wouldn't want to mandate that they are, but requiring them to persist limits implementation options.
Is it to somehow track resets that necessarily also reset the debug module?

**Comment by mwachs5** [comment]
so you're saying just leave it undefined what happens on dmactive = 0?

**Comment by timsifive** [comment]
Yes. Or explicitly state that the those bits might be reset when the debug module is reset.

**Comment by mwachs5** [comment]
What do you mean "when the debug module is reset". The concept of the debug module reset isn't clearly stated anywhere, unless you're referring to dmactive.

**Comment by timsifive** [comment]
I'm trying to imagine when you might want to have havereset bits persist even when dmactive goes low. The only scenario I can think of is when the debugger resets the target (including debug module) completely using eg. a dedicated JTAG pin.

I still think it's better to let the implementation do whatever they like with havereset values when dmactive is low.

**Pull request merged**
