### PR TITLE
Document changes since 0.13.

### PR DESCRIPTION
**Pull request by timsifive**
Excluding clarifications, which don't change the spec.

### CODE REVIEW

**Comment by JamesKenneyImperas** [comment]
Hi Tim,

I find it difficult to read all the changes in this form, but I think some important things are missing. For example, the address of the `scontext` CSR has changed from 0x7AA to 0x5A8, which is completely incompatible. Is this mentioned?

I appended a list of possibilities to issue #584; did you see this?

James.

**Review by ernie-sifive — APPROVED** [review]
This list looks complete to me, given that clarifications are not included in the list.

@JamesKenneyImperas, the scontext address change is mentioned in the list.  It is not backward-incompatible since the original CSR address is still allowed.  (#535). The text in the list for this item should probably also mention the addition of scxe and hcxe.

**Comment by timsifive** [comment]
> I find it difficult to read all the changes in this form

What could we change to make it easier to read?

**Comment by JamesKenneyImperas** [comment]
Hi Tim,

This was down to my inability to use github properly, so please ignore.

Sorry,

James.

**Pull request merged**
